apiVersion: v1
kind: Namespace
metadata:
  name: k8s-papivot-tools
  labels:
    name: k8s-papivot-tools
    app: k8s-papivot-tools
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-obj-dump-sa
  namespace: k8s-papivot-tools
  labels:
    name: k8s-obj-dump
    app: k8s-obj-dump
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-obj-dump-cr
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
    - '*'
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-obj-dump-crb
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-obj-dump-cr
subjects:
- kind: ServiceAccount
  name: k8s-obj-dump-sa
  namespace: k8s-papivot-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: k8s-obj-dump
    app: k8s-obj-dump
  name: k8s-obj-dump-deployment
  namespace: k8s-papivot-tools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-obj-dump
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-obj-dump
        version: v1
    spec:
      containers:
      - env:
        - name: INCLUSTER_CONFIG
          value: "1"      
        - name: GROUPANDVERSION
          valueFrom:
            configMapKeyRef:
              name: game-config-env-file
              key: groupversion
        - name: RESOURCETYPE
          valueFrom:
            configMapKeyRef:
              name: game-config-env-file
              key: resourcetype
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: game-config-env-file
              key: namespace
#          value: ""
        image: us-central1-docker.pkg.dev/navneet-410819/whoami6443-hub/whoami6443/vmkube-watch:0.0.7
        imagePullPolicy: Always
        name: k8s-obj-dump
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 10001
        volumeMounts:
        - mountPath: /app/deleted
          name: config-volume1
        - mountPath: /app/modified
          name: config-volume2
        - mountPath: /app/added
          name: config-volume3
        - mountPath: /user/appuser
          name: cache-volume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        stdin: true
        tty: true
      volumes:
      - name: config-volume1
        configMap:
          name: game-config-env-file
          defaultMode: 0755
          items:
          - key: deleted1.sh
            path: deleted1.sh     
      - name: config-volume2
        configMap:
          name: game-config-env-file
          defaultMode: 0755
          items:
          - key: mod1.sh
            path: mod1.sh     
      - name: config-volume3
        configMap:
          name: game-config-env-file
          defaultMode: 0755
          items:
          - key: added1.sh
            path: added1.sh     
      - name: cache-volume
        emptyDir: {}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-obj-dump-sa
      serviceAccountName: k8s-obj-dump-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config-env-file
  namespace: k8s-papivot-tools
data:
  groupversion: "v1"
  resourcetype: "services"
  namespace: ""
  deleted1.sh: |
    #!/bin/bash    
    echo "$CHANGED_VARIABLE"|jq -r
    echo "delete function"
  mod1.sh: |
    #!/bin/bash
    echo "$CHANGED_VARIABLE"|jq -r
    echo "mod function 1"
  added1.sh: |
    #!/bin/bash
    echo "$CHANGED_VARIABLE"|jq -r
    echo "add function"  
